# Logger Config
logging:
  level:
    com.jhy.app: debug


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #schema: classpath:db/schema-mysql.sql
    #data: classpath:db/data-mysql.sql
    #sql-script-encoding: utf-8
  thymeleaf:
    cache: false
  mail:
      password: 8919007007
      host: smtp.163.com
      username: jihy@kaiyufound.com
      from: jihy@kaiyufound.com
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

app:
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 3600